"""auth

Revision ID: 18b072034668
Revises: ce3c99c6dded
Create Date: 2022-12-29 13:03:13.138182

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '18b072034668'
down_revision = 'ce3c99c6dded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
