"""heroes2

Revision ID: 8d29af36331a
Revises: 57ba8d1a6eb5
Create Date: 2022-12-27 17:46:32.690677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8d29af36331a'
down_revision = '57ba8d1a6eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
